### ISSUE TITLE
Blank dates support

### ISSUE THREAD

**Issue by leszekrogowski** [tombrothers/VfpEntityFrameworkProvider2#14]
VFP OleDb provider represents blank dates as 30-12-1899. Please see screenshots:

VFP:
<img width="457" alt="VFP Pro Studio" src="https://user-images.githubusercontent.com/5956968/49328191-78fe3980-f56c-11e8-8cb0-a846ad235bd9.png">
VFP OleDb:
<img width="374" alt="VFP OleDb" src="https://user-images.githubusercontent.com/5956968/49328194-7d2a5700-f56c-11e8-839f-dc7a8800144d.png">

The problem arrises when blank date column needs to be updated with blank date. The current implementation will just insert / update 30-12-1899. The preferred behaviour should use blank date CTOT(''). It's especially important if VFP database is still used by a legacy system.

**Comment by mPisano** [comment]
This has also plagued me for years with free table DBF's....

When I see a 1899 date, I convert it to 01/01/0001 and do the reverse when saving it.
I used 01/01/0001 since that is what dotnet uses if you convert a null string ex Convert.ToDateTime(null);

Wondering if we are better off fixing this on the read to return 0001?
Or  also store CTOD("") if Date is 0001?

In order to keep things Future Proof...
What does a DBC with a proper DateTime return?
What does a SQL Db under EF do with a null date?

Regards,
Mike

**Comment by leszekrogowski** [comment]
I think we will need some comments from the author but in my opinion it’s possible to return DateTime.MinValue by creating overridden VfpBlankDateTimeDataReader:

```
    public class VfpBlankDateTimeDataReader : VfpDataReader
    {
        public VfpBlankDateTimeDataReader(DbDataReader reader)
            : base(reader)
        {
        }

        public override DateTime GetDateTime(int ordinal)
        {
            var dateTime = base.GetDateTime(ordinal);
            return dateTime > VfpConsts.VfpBlankDate ? dateTime : DateTime.MinValue;
        }
    }
```

and using it in VfpCommand.ExecuteDbDataReader. Then we can modify the SqlFormatter.WriteValue condition to:

```
if ((DateTime)value > VfpConsts.VfpBlankDate)
{
	Write(string.Format("CTOT('{0:yyyy-MM-dd}T{0:HH:mm:ss}')", value));
}
else
{
	// Blank date support
	Write("CTOT('')");
}
```

Do you think that such approach will be better than using 1899-12-30?

> Answering your further questions:

What does a DBC with a proper DateTime return?
I’m not using free tables, but DBC so DateTime behaviour shouldn’t be dependent on it.

> What does a SQL Db under EF do with a null date?

I’m not sure exactly what do you mean by this question but in Vfp provider for inserting / updating null DateTimes it just uses NULL:

SqlFormatter.WriteValue:

```
if (value == null) {
    Write("NULL");
}
```

Best regards,
Leszek

**Comment by tombrothers** [comment]
@leszekrogowski you can use [IDbCommandInterceptor](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.interception.idbcommandinterceptor?view=entity-framework-6.2.0) to rewrite the query.

**Comment by leszekrogowski** [comment]
@tombrothers  you are right if we are going to ignore @mPisano comment. However, I still have a feeling that it should be supported at the provider level.

**Comment by leszekrogowski** [comment]
If anyone has similar problem, I have used the following interceptor which seems to work for my use cases:

```
    public class VfpBlankDateInterceptor : IDbCommandInterceptor
    {
        public void NonQueryExecuted(DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
        {
        }

        public void NonQueryExecuting(DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
        {
            ReplaceVfpBlankDate(command);
        }

        public void ReaderExecuted(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
        {
        }

        public void ReaderExecuting(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
        {
        }

        public void ScalarExecuted(DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
        {
        }

        public void ScalarExecuting(DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
        {
            ReplaceVfpBlankDate(command);
        }

        private static void ReplaceVfpBlankDate(DbCommand command)
        {
            command.CommandText = command.CommandText.Replace("CTOT('1899-12-30T00:00:00')", "CTOT('')");
        }
    }
```

and add it as usual to interceptors:

`DbInterception.Add(new VfpBlankDateInterceptor());`

I believe that issue can be closed and PR abandoned.
