### ISSUE TITLE
Include "Deleted" Rows in Query

### ISSUE THREAD

**Issue by MarkPowWorkman** [tombrothers/VfpEntityFrameworkProvider2#16]
Hi,

I'm probably missing something obvious but how do you include "deleted" rows in the query using the Entity Framework?

If I run the same query using Visual Fox Pro the rows show up (albeit marked as deleted), however running the same query through the entity provider, the deleted rows do not show...

Any help would be much appreciated.

Kind regards,

Mark

**Comment by tombrothers** [comment]
You need to add “Deleted=true” to the connection string.

**Comment by MarkPowWorkman** [comment]
Thanks Tom, it reports "Keyword not supported: 'deleted'." 

I'm adding "Deleted=true" to the connection string in app.config.

**Comment by tombrothers** [comment]
I'm not sure why you are getting that errors.  I tested this out and found that I had the setting backwards.  It should have been false... but other than that it worked as I suggested.  Here is the connection setting that I used.
`<add name="Northwind" connectionString="data source=c:\NorthwindData\Northwind.dbc;deleted=false" providerName="VfpEntityFrameworkProvider2"/>`

**Comment by MarkPowWorkman** [comment]
Thanks Tom, it was because I was being a ninny and put the flag in the wrong place!

Many thanks for your help and quick response.
