### ISSUE TITLE
The underlying provider failed on Open.

### ISSUE THREAD

**Issue by cvivieca** [tombrothers/VfpEntityFrameworkProvider2#17]
I built my app and run it on a different computer and I'm getting this error. 

`The underlying provider failed on Open. en System.Data.Entity.Core.EntityClient.EntityConnection.Open()`

I installed VfpEntityFrameworkProvider and VfpClient on that computer but I'm still getting the error.

Has anyone had the same error?

**Comment by mPisano** [comment]
I would initially think your app config files has a missing provider or incorrect connection string?

Could possible be a bad path or rights?

I would also rerun the VFPOLEDBSetup.msi as an Admin and make sure its for All Users

**Comment by cvivieca** [comment]
Actually my connections string is the next: 

```
    <add name="InteliInventoryContext" connectionString="metadata=res://*/Persistences.IntelifarmaContext.InteliInventoryContext.csdl|res://*/Persistences.IntelifarmaContext.InteliInventoryContext.ssdl|res://*/Persistences.IntelifarmaContext.InteliInventoryContext.msl;provider=VfpEntityFrameworkProvider2;provider connection string=&amp;quot;data source=Z:\inteliPHARMA\DATA\dbinventario.dbc;deleted=True;null=False&amp;quot;"
      providerName="System.Data.EntityClient" />
```

I'm using the same connection generated by the provider went I generated the EDMX model. The same is working on my PC I just change the path and the path exists. 

I will try installing VFPOLEDBSetup.msi for all users

**Comment by cvivieca** [comment]
I add a space between `provider=VfpEntityFrameworkProvider2;{SPACE HERE}provider connection string` and know I'm getting the following error. 

![image](https://user-images.githubusercontent.com/22035782/80649926-e7d11200-8a40-11ea-9bf5-eb9477a58442.png)

It's curious because I'm using the same connection string that works on my machine.

**Comment by mPisano** [comment]
I'm not sure the string you use for the EDMX model you would use at runtime... I only use code first?
After the model is built and at runtime I think you can just use a normal connection string? 

Here is my default template I use in my projects. You can try your connections string too, but try adding the provider and factories.

```
Below:
<connectionStrings> needs to match your class (ie EFDbContext )

<providers> Needed For EF

<system.diagnostics> is optional and I leave it commented out unless there is an issue

<DbProviderFactories> Let me keep the VfpClient.dll and VFPEFProvider.dll DLL's local to my EXE and only need the VFP OleDB driver to be installed system wide.
```

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="EFDbContext" providerName="VfpEntityFrameworkProvider2" connectionString="data source=C:\DBFPATH;deleted=True;null=False;enginebehavior=90;CODEPAGE=1252;"/>
  </connectionStrings>

  <entityFramework>
    <providers>
      <provider invariantName="VfpEntityFrameworkProvider2" type="VfpEntityFrameworkProvider.VfpProviderServices, VfpEntityFrameworkProvider"/>
    </providers>
  </entityFramework>

  <system.diagnostics>
    <trace autoflush="true"/>
    <sources>
      <source name="VfpClient" switchValue="All">
        <listeners>
          <add name="VfpClientTextWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\Trace\VFPEFTrace.txt"/>
        </listeners>
      </source>
    </sources>
  </system.diagnostics>

  <system.data>
    <DbProviderFactories>
      <clear/>
      <add name="Vfp Entity Framework Provider" invariant="VfpEntityFrameworkProvider2" description="Vfp Entity Framework Provider" type="VfpEntityFrameworkProvider.VfpProviderFactory, VfpEntityFrameworkProvider"/>
    </DbProviderFactories>
  </system.data>
</configuration>
```

**Comment by cvivieca** [comment]
Hey Mike, 

I solved my problem adding **double quote** instead of using **&amp;quot;** on connection string. Sorry for taking so long to respond.

**Comment by mPisano** [comment]
No worries - Glad its fixed!
