### ISSUE TITLE
Has anyone used VfpEntityFrameworkProvider2 with EFCore (any version?)

### ISSUE THREAD

**Issue by MikeYeager** [tombrothers/VfpEntityFrameworkProvider2#21]
I'm wondering if I can use it in an EFCore 7 project. The NuGet package installs, but will it work? the first question I have is that .NET 7 projects use appconfig.json files and not app.config XML files. I have no idea how to enter the configuration in json. I could read the settings manually and then set them in code, but it would be nice if I didn't have to. Thank you in advance.

**Comment by mPisano** [comment]
Hey Mike,

At last Tom had added some changes for NETSTANDARD2_1 and NET5... its been years now and I'm not sure what\if any provider changes are necessary for EF CORE... I'm about to start a new project that also needs to touch the VFP tables and was also wondering about compatibility.

There are tons of articles about porting to EF Core (6 & 7) none for VFP, but the concept is the same. 
From looking at the SQL json examples the VFP should look like the below
{
  "ConnectionStrings": {
    "FoxConnectionString": "Data Source=c:\test\;deleted=True;null=False;enginebehavior=90;CODEPAGE=1252;",
    "ProviderName": "VfpEntityFrameworkProvider2"
  }
}
not sure how to set the "DbProviderFactories"... looks like that might need to be done in code now...
Are there any errors you are getting? 
If you can get together a sample, maybe we can figure it out or see what's necessary on updating the provider.
Also - Remember you still need to build for 32 bit

Mike

**Comment by tombrothers** [comment]
This project can't be used with EF Core. I started an EF Core version awhile back but lost interest. You could use this as a starting point if you wanted to create an EF Core provider.
https://github.com/tombrothers/EntityFrameworkCore.Vfp

**Comment by MikeYeager** [comment]
@tombrothers thank you for the reply. I think I'll just stick with EF 6. Nursing this old technology along is painful. Here's to hoping it doesn't last forever :-). 

@mPisano I was able to use ASP.NET 7 (but not EF Core 7) by configuring it manually. I added this class in the same assembly as the rest of my EF code:
`    //The existence of this class in this assembly causes EF to be configured without accessing the config file
    public class VfpConfiguration : DbConfiguration
    {
        public VfpConfiguration()
        {
            DbProviderFactories.RegisterFactory("VfpClient.VfpClientFactory", VfpClient.VfpClientFactory.Instance);
            SetProviderServices("VfpClient.VfpClientFactory", VfpEntityFrameworkProvider.VfpProviderServices.Instance);
        }
    }`

Then in my context I did something like this:
`    public partial class TestDataEntities : DbContext
    {
        public TestDataEntities()
        {
            Database.Connection.ConnectionString = "Data Source=<C:\\Data\\...>; deleted=true; null=false; enginebehavior=90; codepage=1252";
        }`

Notice, I don't call the base constructor. I'll manually read the configuration and use that in place of a static string, but haven't gotten around to that yet.

Everything works great so far.
