### ISSUE TITLE
IIS Session timeout leaves foxpro files open

### ISSUE THREAD

**Issue by Oldergit** [tombrothers/VfpEntityFrameworkProvider2#3]
When the IIS Session times out it would appear to leave some foxpro files open. They appear to be attached to process w3wp.exe for the AppPool used for our application. How do I close these files without corrupting any index files?

After a while the files appear to be shut down of their own accord. Can I set some timeout function in VfpEntityFrameworkProvider2 to shut the files down or is there some other process I can use to close these files down gracefully?

**Comment by mPisano** [comment]
Oldergi,

All of my web calls generally Open, query and Close using an MVC approach.
If the session times out, the result set might fail to be sent back, but the files are closed.

Could it be a query time-out and a missing catch try block?
Also, move all session variables to local vars before you do you open so your thread safe until you close.

You can lower the default session timout of 20 min in the web.config, but I don't know what the state would be of the CDX especially if your writing rows.
https://msdn.microsoft.com/en-us/library/h6bb9cz9%28vs.80%29.aspx

if not, give us some more details on your code and maybe it will shed some more light

HTH,
Mike PIsano

**Comment by Oldergit** [comment]
Mike

Thanks for that but I don't have that sort of control as the model I am using closes and opens the files I need to use. It is a code first model and uses a Breeze library. I was hoping there might be a "switch" I could set when VfpEntityFramework2 is loaded in an IIS environment.

**Comment by mPisano** [comment]
I also am using Breeze in my application, but breeze only handles passing the iQuerayble and JSON back along with the metadata from the model. I still have complete control over the creation and destruction of the my DAL object?

You mentioned "Some Files" do you know if these handles are directly related to timeouts, and can you reproduce it?

Mike

**Comment by Oldergit** [comment]
We have discovered that we need to dispose of our context - which seems to shut down the files causing problems - but not always.

**Comment by mPisano** [comment]
Make sure you use a Try/Catch or Using statement around your DAL context.

By problems, do you mean your CDX's are corrupted? Are you using free tables,  or do you have a DBC?

**Comment by Oldergit** [comment]
We are just checking the files are being shut down when logged out of the web site or the session has expired. The testing is to avoid corrupted CDX's and attempting not to hold the files open when other processes need exclusive access. We have a DBC. We have tried the a similar test in foxpro and the files are held open until the foxpro session is ended even though a close all is issued.

I had discovered if I manually restart IIS it seemed to release the files. So I wrote a little test application to close the Default Web Site IIS entry for five seconds last night but the files still appear to be open and attached to the Application Pool.

**Comment by mPisano** [comment]
Strange - shutting down the IIS server should close all the app pools and release the handels? 

Are the files on the same server or across the net, and if so are you using SMB or NFS?
What server OS/IIS Version? and is your application pool configured for clasic or integrated pipeline?

If you have some sample project it might be easier to look at it.

Mike

**Comment by Oldergit** [comment]
Actually recycling the App Pool with some C# code seems to do the trick without restarting IIS. It is running on IIS 7 and 8.5 on a server and a local windows PC.

**Comment by mPisano** [comment]
Shutting down the App Pool is much like an "End Task" to the data Handles, which is the same as the timeout close. I still worry about any unflushed data, or CDX corruption.
Also, unless you can guarantee nobody is using the site when c# closes them, you could corrupt any open transactions when you bump the users off.

I think your context is not destroying, or some other internal object is not released until garbage collection. I would use sysinternals (bought by microsoft) "Process Explorer" and see what files have locks and figure out the underlying issue.

I Just doubled checked my app, If I end task my browser after clicking a bunch of query operations, I can see the IIS handles being shut down within a minute.

Mike

**Comment by Oldergit** [comment]
I have just modified the code to check the sessions linked to the App Pool. If any sessions exist the pool is not recycled. However now I discover after a log out has been performed on the web site the App Pool entries for sessions still show one exists! I assume it will time out eventually and allow my application to recycle the App Pool. Most of the queries are reading data. We will be testing saves once this is working.

**Comment by Oldergit** [comment]
We have now found that even though we are disposing of the context it is not closed correctly until garbage collection is called. So once we have disposed of a context we then force a garbage collection.

Like so:

```
                        context.Dispose();
                        GC.Collect();
```

**Comment by mPisano** [comment]
interesting,

The GC.Collect could be something inside the provider - do you have a small sample program we can use to duplicate it?

Thanks,
Mike

**Comment by Oldergit** [comment]
Hi Mike

Unfortunately there is no sample program. We have used it inside one of our providers but the quick solution was to do the GC.Collect elsewhere. Even in a pure c# application (without IIS) it was causing a problem.
