### ISSUE TITLE
All columns are being reported as Keys

### ISSUE THREAD

**Issue by ontytoom** [tombrothers/VfpEntityFrameworkProvider2#6]
I am running into an issue that all columns in my 240-column VFP table are being reported as keys. This makes it difficult to split this entity into multiple, which is needed because Select statement for this table is 16,000 characters long.

I am not entirely sure if this is happening due to a limitation/bug in your component, or perhaps actual DB structure. 

Below screen shots show an error I am receiving when trying to split an entity into 2 and excluding some columns:
![image](https://cloud.githubusercontent.com/assets/1593655/25965388/d043f266-3655-11e7-87aa-89c65c374e4f.png)

This screen shot shows that many columns are considered keys. In fact, I have so many columns in this table that they all don't fit on the screen at once, but they are all considered keys:
![image](https://cloud.githubusercontent.com/assets/1593655/25965455/0a2c9712-3656-11e7-92be-06063508f945.png)

There is a small possibility that this is due to the actual underlying VFP database. I am researching....

**Comment by tombrothers** [comment]
The following two blog entries explain why that occurs and gives you an idea on how you can resolve the issue.

[Using VFP Entity Framework Provider With Free Tables](https://randomdevnotes.com/2012/02/05/using-vfp-entity-framework-provider-with-free-tables/)
[Using VFP Entity Framework Provider With Free Tables Using Code First](https://randomdevnotes.com/2012/05/06/using-vfp-entity-framework-provider-with-free-tables-using-code-first/)

**Comment by ontytoom** [comment]
Tom, many thanks for the info! I am reviewing.

**Comment by ontytoom** [comment]
I just found out that the table in question has no Primary Index, hence the behavior. Your component is working as expected. I am closing the issue.
